version: "3"
services:
  front:
    build: ./frontend
    links:
      - api
    depends_on:
      - api

  api:
    links:
      - postgres
    build: ./backend
    environment:
      DbConnect: "Server=postgres;port=5432;Database=postgres;User Id=postgres;Password=root"
    env_file:
      - back.env
    depends_on:
      - postgres
    ports:
      - 5000:80

  postgres:
    build: ./postgres
    environment:
      POSTGRES_PASSWORD: root
